# Use an official Node runtime as a parent image
FROM node:16

# Set the working directory in the container
WORKDIR /app/frontend

# Copy package.json AND package-lock.json before other files
# Utilize Docker cache to save re-installing dependencies if unchanged
COPY . /app

# Install app dependencies
RUN npm install

# Build the app for production
RUN npm run build

# Install serve to run the application
RUN npm install -g serve

# Serve the app on port 3000
CMD ["serve", "-s", "build", "-l", "3000"]

# Make port 3000 available outside this container
EXPOSE 3000
